/home/hua/anaconda2/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  .format(x=modname), ExtDeprecationWarning
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
/home/hua/anaconda2/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  .format(x=modname), ExtDeprecationWarning
 * Debugger is active!
 * Debugger pin code: 215-816-369
127.0.0.1 - - [30/Nov/2023 22:09:32] "GET /static/clientinstall/Linux86_64.zip HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/hua/anaconda2/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/hua/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/hua/anaconda2/lib/python2.7/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/home/hua/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hua/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hua/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hua/anaconda2/lib/python2.7/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/home/hua/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hua/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hua/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hua/anaconda2/lib/python2.7/site-packages/flask/helpers.py", line 892, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/hua/anaconda2/lib/python2.7/site-packages/flask/helpers.py", line 633, in send_from_directory
    filename = safe_join(directory, filename)
  File "/home/hua/anaconda2/lib/python2.7/site-packages/flask/helpers.py", line 603, in safe_join
    return os.path.join(directory, filename)
  File "/home/hua/anaconda2/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 10: ordinal not in range(128)
